### ISSUE TITLE
Moya version

### ISSUE THREAD

**Issue by philosopherdog** [levibostian/Lucid#11]
Just wondering what the status of support for Moya 12 is. Thanx.

**Comment by levibostian** [comment]
Hello there, @philosopherdog. Thanks for asking. 

At this time, I am not planning on updating the repo with Moya 12. I no longer use Lucid for new apps of mine, I only keep it maintained for older apps that I have created and still use Lucid. 

The problem that Lucid is solving, I still have in my apps. However, I have begun to solve the problem in a different way. One to follow the ReactiveX best practices better. And create a better API, in my opinion. 

I am not sure if I will create a new repo with this new proposed solution, or edit this one with my new way of solving the problem. It would be a breaking change update with a completely new API. 

---

That is the future. Now, about the present: 

I have not updated this repo README with the message I have given you above. So therefore, I take it as my responsibility to keep it maintained for people to use until I make this announcement. 

If you would like Moya 12 support, please feel free to make a pull request with Moya 12 as well as Swift 4.2.

I would appreciate the help with a pull request. However, I am also happy to update the project with the updates if you wish. 

Thank you so much for enjoying Lucid, @philosopherdog. 

I made a note to write up an announcement with my proposed future of Lucid. I will mention you on the GitHub issue created so that you can see it and give feedback on it. 

Peace, 
Levi
